[build-system]
requires = ["setuptools", "wheel", "torch"]
build-backend = "setuptools.build_meta"

[project]
name = "metalcore"
# Version is managed in src/metalcore/__init__.py
# setup.py reads it dynamically
dynamic = ["version"]
description = "Foundational Metal Linear Algebra Primitives for PyTorch"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}

authors = [
  { name = "Kris Bailey", email = "kris@krisbailey.com" }
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Operating System :: MacOS :: MacOS X",
]
dependencies = [
    "torch>=2.0",
    "numpy"
]

[project.urls]
"Homepage" = "https://github.com/myfykris/metalops"
"Bug Tracker" = "https://github.com/myfykris/metalops/issues"
